### ISSUE TITLE
detection of malicious functionality or code in the legitimate binary 

### ISSUE THREAD

**Issue by nav60** [evandowning/deepreflect#3]
Hi,
Sir,
Thanks for sharing wonder work and it is an interesting and tough research area. I am going to start work in this area however right now i am confused in many things. However, i came across this wonderful work. 
I have query after reading your paper . As you mentioned that you are going to use malware as a input . However, can i use legitimate binary which contains malicious working, can work in your code or not. I mean malicious working in a legal program like calculator, can we detect its malicious functionality via this method or not. can you give your opinion on it. please

**Comment by evandowning** [comment]
Hello. Thank you for your question about our work.

Conceptually yes, although we did not evaluate this in our paper, you can submit a legitimate binary which contains malicious functionalities (usually called a "trojan") to DeepReflect and it will identify that malicious functionality (assuming the legitimate functionalities have been seen/trained by the autoencoder before).

However, this is mostly useful for _unknown_ legitimate binaries. I.e., a custom calculator program someone has written as opposed to one like Windows Calculator which is well-known. That is, if you have malicious functionality in Windows Calculator, you can just simply compare it to a legitimate version and identify the differences as malicious logic (of course assuming you know you have two supposedly identical versions of Windows Calculator).

Does this answer your question?

**Comment by nav60** [comment]
Yes sir. 
This is my understanding and may be wrong. 
but differences between two binaries does not mean that different part is malicious. that different part will be analyzed by your tool to verify that is it malicious or not ?? I am having issue to run your code so that why i am asking such questions. 
can i approach you over email if it possible for you?

**Comment by evandowning** [comment]
I think it's fine if we take this conversation to email.

For now I will close this issue. If anything helpful can be added to the documentation after our email conversation, I will do so.
