### ISSUE TITLE
porting of python code for IDAPRO python

### ISSUE THREAD

**Issue by nav60** [evandowning/deepreflect#5]
Hi, 
Sir, I need some assistance if possible for you. As I am trying to use IDAPRO instead of BN tool, so for this first i have understand your "extraction" code of python and found following 4 relevant files.
![image](https://user-images.githubusercontent.com/34056389/124612273-a1204880-de8b-11eb-9ce9-84db53820635.png)

Please guide me if you find any problem in my understanding of code flow and conversion.
1. binja.py
in this file, BNDB files created against the binaries.  I have done the same for IDAPRO however i have skipped it and moved to 
2. extract_raw.py file. After understand of code flow, i have done following .
a). implemented get_dr_binja function.   After loading binary, implemented CFG part (basicblock and networkx part) , converted instruction assembly yet.

Can you please comment on my understanding of your code flow for BN part and my implementation flow part as well.  I will be thankful to you.

**Comment by nav60** [comment]
Sir, 
I have converted extract_raw.py code with respect to IDAPRO and notepad.exe is use as a exe to verify this file. I am sharing my result for this exe. if possible then please share BN result for the same file. 
Sir. as i have downloaded "dataset" from your project page and found "malware-gt-binja" folder. It contains .txt files of malware exe and content of each file (i.e   carbanak_autorunsidebar.txt) is shown below

![image](https://user-images.githubusercontent.com/34056389/125041426-300eaa00-e0b2-11eb-875c-1e504dcf311a.png)
 
Sir. i have saved dump like above in dump.txt and output of each step in .txt file to check the output.

Is it possible for you to comment on this.

**Comment by nav60** [comment]
Update:
Sir, as i have .txt output for carbanak_botcmd.txt and carbanak_bot.txt and i run mt program on both exe's of malware.  Till now result are different and BB's count is differ in my output file. I could not understand it yet why BB's count is different. BB's are less compared to your shared output

**Comment by evandowning** [comment]
Hi @nav60 ,

> Till now result are different and BB's count is differ in my output file. I could not understand it yet why BB's count is different. BB's are less compared to your shared output

I imagine this is because IDA Pro's disassembly differs from BinaryNinja's disassembly. This is because they use different (proprietary) heuristics to determine where (and what) functions and basic blocks are.

Regardless of this difference, if you were to train the model on benign binaries and test on malicious binaries (using IDA Pro throughout), you will still be able to use DeepReflect's methodology to discover malicious functionalities within malware binaries.

Thanks,
Evan

**Comment by nav60** [comment]
Ok sir. Thank you sir. I am working on it.
