### ISSUE TITLE
Traceback (most recent call last):   File "<stdin>", line 1, in <module>   File "/root/.virtualenvs/dr/lib/python3.7/site-packages/numpy/lib/npyio.py", line 444, in load     raise ValueError("Cannot load file containing pickled data "

### ISSUE THREAD

**Issue by zijiancogito** [evandowning/deepreflect#6]
I used features download from Dataset.md/feature.tar.gz. Then I tried to run the command "python feature_check.py train.txt", where "train.txt" was copied from "Dataset.md/models.zip". It would raised aboved errors. What's wrong with it?

**Comment by nav60** [comment]
Hi,
feature_check.py required .npy files to perform required operation. Open the train.txt or test.txt and see the path of the file. do you have files in this path. If not then extract the feature.tar.gz and place as given in the train.txt and test.txt . You have to do some manual work to correct path. Hope it will help

**Comment by zijiancogito** [comment]
Thank you! I fix this by using files in *_plus_feature/.

**Comment by evandowning** [comment]
@zijiancogito Would you like for me to add additional documentation mentioning this?

**Comment by zijiancogito** [comment]
Yes. I think so.
