### ISSUE TITLE
time python pca_hdbscan.py --cfg cluster.cfg  > pca_hdbscan_stdout.txt

### ISSUE THREAD

**Issue by zijiancogito** [evandowning/deepreflect#8]
Traceback (most recent call last):
  File "pca_hdbscan.py", line 16, in <module>
    import hdbscan
  File "/home/user/anaconda3/envs/dr/lib/python3.7/site-packages/hdbscan/__init__.py", line 1, in <module>
    from .hdbscan_ import HDBSCAN, hdbscan
  File "/home/user/anaconda3/envs/dr/lib/python3.7/site-packages/hdbscan/hdbscan_.py", line 21, in <module>
    from ._hdbscan_linkage import (single_linkage,
  File "hdbscan/_hdbscan_linkage.pyx", line 1, in init hdbscan._hdbscan_linkage
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject

real    0m0.646s
user    0m2.506s
sys     0m2.723s
what's wrong with me?

**Comment by evandowning** [comment]
This is most likely an issue with the version of hdscan & Python3 you're using: https://github.com/scikit-learn-contrib/hdbscan/issues/457

You might try reinstalling the package with additional flags as described here: https://github.com/scikit-learn-contrib/hdbscan/issues/457#issuecomment-770917067

For my implementation I used hdbscan 0.8.27 (as seen in the requirements.txt file) and Python 3.7.3.

**Comment by nav60** [comment]
I have also faced similar problem which was due to scikit-learn version. I have changed it from 1.0 to 0.24.2 which was working on the 1st machine.

**Comment by zijiancogito** [comment]
Thank you. I had fixed it by reinstall scikit-learn.
